// Pure SQL generator for the movements seed.
//
// Lives in the domain layer (not scripts/) so it can be unit-tested
// under the workers-pool vitest runner without dragging in Node-only
// child_process + fs imports. The CLI glue in scripts/db/seed-movements.ts
// imports from here.

import type { MovementType, MovementStatus } from "@/db/schema";

export interface SeedRow {
  id: string;
  canonical_name: string;
  manufacturer: string;
  caliber: string;
  type: MovementType;
  status: MovementStatus;
  notes?: string;
}

const VALID_TYPES: readonly MovementType[] = [
  "automatic",
  "manual",
  "quartz",
  "spring-drive",
  "other",
];
const VALID_STATUSES: readonly MovementStatus[] = ["approved", "pending"];

function sqlQuote(value: string | null): string {
  if (value === null) return "NULL";
  // SQLite quoting: double any single quote; no backslash escapes.
  return "'" + value.replace(/'/g, "''") + "'";
}

function rowToSql(row: SeedRow): string {
  if (!VALID_TYPES.includes(row.type)) {
    throw new Error(`invalid type for id=${row.id}: ${row.type}`);
  }
  if (!VALID_STATUSES.includes(row.status)) {
    throw new Error(`invalid status for id=${row.id}: ${row.status}`);
  }
  const cols = "id, canonical_name, manufacturer, caliber, type, status, notes";
  const values = [
    sqlQuote(row.id),
    sqlQuote(row.canonical_name),
    sqlQuote(row.manufacturer),
    sqlQuote(row.caliber),
    sqlQuote(row.type),
    sqlQuote(row.status),
    sqlQuote(row.notes ?? null),
  ].join(", ");
  return `INSERT OR IGNORE INTO movements (${cols}) VALUES (${values});`;
}

function validateSlugs(rows: SeedRow[]): void {
  const seen = new Set<string>();
  for (const row of rows) {
    if (!/^[a-z0-9][a-z0-9-]*$/.test(row.id)) {
      throw new Error(`invalid slug: ${row.id} (must be kebab-case)`);
    }
    if (seen.has(row.id)) {
      throw new Error(`duplicate slug: ${row.id}`);
    }
    seen.add(row.id);
  }
}

/**
 * Build an idempotent, transactional SQL script that inserts the given
 * movement rows. Uses `INSERT OR IGNORE` keyed on the `movements.id`
 * PK so re-runs are a no-op.
 */
export function buildSeedSql(rows: SeedRow[]): string {
  validateSlugs(rows);
  const header = [
    "-- Generated by scripts/db/seed-movements.ts — do not commit.",
    "-- Idempotent: INSERT OR IGNORE keyed on the movements.id PK.",
    "--",
    "-- No BEGIN/COMMIT wrapper: D1 rejects explicit transactions in SQL",
    "-- (see workerd error 'To execute a transaction, please use the state.storage',",
    "-- which is DO-specific guidance that spills into D1's wrangler path).",
    "-- Each INSERT auto-commits; INSERT OR IGNORE keeps the batch idempotent.",
  ];
  const body = rows.map(rowToSql);
  return [...header, ...body].join("\n") + "\n";
}
