"""Tests for `dial_reader.image_decoder`.

The decoder is the first piece of the container that does real work.
Its responsibility is split in two:

  1. Format validation by magic-byte sniffing. We never trust the
     `Content-Type` header — clients lie / are buggy / get exploited.
  2. Decode-or-die. Supported formats land in the dispatcher;
     unsupported ones raise a typed `UnsupportedFormatError`;
     anything that the underlying decoder fails on raises
     `MalformedImageError`.

Both error classes are caught at the HTTP layer and mapped to
distinct response shapes (rejection-with-200 vs error-with-400),
so the test surface keeps them strictly separate.

Fixtures live in `conftest.py` and are generated by Pillow at test
collection time so the diff stays text-only.
"""

from __future__ import annotations

import numpy as np
import pytest

from dial_reader.image_decoder import (
    MalformedImageError,
    UnsupportedFormatError,
    decode,
)

# ---------------------------------------------------------------
# Successful decode paths — one test per supported format.
# Each format dispatches into a different code path internally
# (Pillow vs pillow-heif), so the per-format tests are real
# coverage rather than redundant.
# ---------------------------------------------------------------


def _assert_rgb_ndarray(arr: object, *, height: int = 4, width: int = 4) -> None:
    """Common assertion: result is HxWx3 uint8 ndarray of expected shape."""
    assert isinstance(arr, np.ndarray)
    assert arr.dtype == np.uint8
    assert arr.shape == (height, width, 3)


def test_decode_jpeg_returns_rgb_ndarray(jpeg_bytes: bytes) -> None:
    arr = decode(jpeg_bytes)
    _assert_rgb_ndarray(arr)


def test_decode_png_returns_rgb_ndarray(png_bytes: bytes) -> None:
    arr = decode(png_bytes)
    _assert_rgb_ndarray(arr)


def test_decode_webp_returns_rgb_ndarray(webp_bytes: bytes) -> None:
    arr = decode(webp_bytes)
    _assert_rgb_ndarray(arr)


def test_decode_heic_returns_rgb_ndarray(heic_bytes: bytes) -> None:
    """HEIC is the iPhone-camera default; the entire CV pipeline
    is dead in the water if this branch doesn't work."""
    arr = decode(heic_bytes)
    _assert_rgb_ndarray(arr)


# ---------------------------------------------------------------
# Unsupported-format rejection paths.
# Each of these is something Pillow could decode if we asked it
# to, but we explicitly refuse: the upstream verifier flow only
# wants the four formats above, and accepting GIFs / TIFFs etc.
# would be a tail of niche regressions later.
# ---------------------------------------------------------------


def test_decode_gif_raises_unsupported(gif_bytes: bytes) -> None:
    with pytest.raises(UnsupportedFormatError):
        decode(gif_bytes)


def test_decode_bmp_raises_unsupported(bmp_bytes: bytes) -> None:
    with pytest.raises(UnsupportedFormatError):
        decode(bmp_bytes)


def test_decode_tiff_raises_unsupported(tiff_bytes: bytes) -> None:
    with pytest.raises(UnsupportedFormatError):
        decode(tiff_bytes)


def test_decode_avif_raises_unsupported(avif_bytes: bytes) -> None:
    """AVIF and HEIC share the ISO BMFF container — the decoder
    must inspect the brand, not just `ftyp`."""
    with pytest.raises(UnsupportedFormatError):
        decode(avif_bytes)


def test_decode_random_bytes_raises_unsupported(random_bytes: bytes) -> None:
    with pytest.raises(UnsupportedFormatError):
        decode(random_bytes)


# ---------------------------------------------------------------
# Malformed-input paths.
# These surface as 400 at the HTTP layer rather than the
# rejection-with-200 used for unsupported-but-recognised formats.
# ---------------------------------------------------------------


def test_decode_empty_bytes_raises_malformed() -> None:
    with pytest.raises(MalformedImageError):
        decode(b"")


def test_decode_truncated_jpeg_raises_malformed(truncated_jpeg_bytes: bytes) -> None:
    """First 100 bytes still sniff as JPEG (magic `FF D8 FF` is
    intact), so the decoder dispatches into Pillow and Pillow then
    fails on the missing data — surfaces as MalformedImageError."""
    with pytest.raises(MalformedImageError):
        decode(truncated_jpeg_bytes)


# ---------------------------------------------------------------
# The decoder is byte-driven, not header-driven. This is the
# test that protects against a regression where someone "helpfully"
# adds Content-Type-based dispatch.
# ---------------------------------------------------------------


def test_decode_is_byte_driven_not_header_driven(jpeg_bytes: bytes) -> None:
    """JPEG bytes labeled as anything else still decode as JPEG.

    The function takes raw bytes; there's no header to consult.
    This test is the regression contract: any future change that
    routes by content-type rather than magic-bytes will fail here.
    """
    arr = decode(jpeg_bytes)
    _assert_rgb_ndarray(arr)
